---
title: "iButtons2022"
author: "Jana Peirce, Emily Watson-Cook"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(scales)
```

```{r}
ibtn_temp <- read.csv("../data/ibtn_temp_tbl.csv")

head(ibtn_temp)
```

```{r}
temp_long <- ibtn_temp %>% 
  pivot_longer(cols = c(-Date, -Time), names_to = "iBtn_ID", values_to = "temp_c")

head(temp_long)
```

## Questions
- why do I have to run libraries and reset variables every time I restart RStudio desktop?
- why do column heads that are numbers become characters (X002) when converted to a col variable in a long format?
- using git with desktop r studio?

```{r}
plot_type <- read.csv("../data/plot_type_tbl.csv")

head(plot_type)
```

```{r}
iBtn_summary <- left_join(temp_long, plot_type, by = c("iBtn_ID"))

head(iBtn_summary)
```

```{r}
write.csv(iBtn_summary, "C:\\Users\\jlpeirce\\OneDrive - University of Alaska\\R for UAF AGC\\nna-irps\\iButtons\\data\\iBtn_summary.csv", row.names = FALSE)
```

```{r}
avg_daily_temp <- iBtn_summary %>%
  group_by(Date, iBtn_ID, Sensor_type, Plot_type) %>% 
  summarize(avg_daily_temp = mean(temp_c, na.rm = T), .groups = "drop")

avg_daily_temp
```

```{r}
write.csv(avg_daily_temp, "C:\\Users\\jlpeirce\\OneDrive - University of Alaska\\R for UAF AGC\\nna-irps\\iButtons\\data\\iBtn_adt_all.csv", row.names = FALSE)
```

```{r}
p <- ggplot(avg_daily_temp, aes(x = Date, y = avg_daily_temp, color=Sensor_type)) +
  geom_point()

p
```

```{r}
p <- ggplot(avg_daily_temp, aes(x = Date, y = avg_daily_temp, color=Plot_type)) +
  geom_point() 

p
```

```{r}
adt_sensor_type <- iBtn_summary %>% 
  group_by(Date, Sensor_type) %>% 
  summarize(avg_daily_temp = mean(temp_c, na.rm = T), .groups = "drop")

head(adt_sensor_type)

write.csv(adt_sensor_type, "C:\\Users\\jlpeirce\\OneDrive - University of Alaska\\R for UAF AGC\\nna-irps\\iButtons\\data\\adt_sensor_type.csv", row.names = FALSE)
```

```{r}
sensor_type <- iBtn_summary %>% 
  group_by(Sensor_type) %>% 
  summarize(avg_sensor_type = mean(temp_c, na.rm = T), .groups = "drop")

head(sensor_type)

write.csv(adt_sensor_type, "C:\\Users\\jlpeirce\\OneDrive - University of Alaska\\R for UAF AGC\\iButtons\\data\\sensor_type.csv", row.names = FALSE)
```

```{r}
p <- ggplot(avg_daily_temp, aes(x = Date, y = avg_daily_temp)) +
  geom_point() +
  facet_wrap(~Sensor_type, ncol=2) +
  labs(x = "Date", y = "degrees C") +
  theme_bw()

p
```

```{r}
avg_iBtn_temp <- iBtn_summary %>%
  group_by(iBtn_ID, Sensor_type, Plot_type) %>% 
  summarize(avg_temp = mean(temp_c, na.rm = T), .groups = "drop")

avg_iBtn_temp
```